# Hello-friends
##First plot
datos=read.table(file.choose(),header=T,sep=';')
datos=transform(datos,Date=as.Date(Date,format='%d/%m/%Y'))
datos=subset(datos,Date>as.Date('2007-01-31'))
datos=subset(datos,Date<as.Date('2007-02-03'))
png(file='plot4.png')
par(mfrow=c(2,2))
plot(time,datos$Global_active_power,type='l')
plot(time,datos$Voltage,type='l')
plot(time,datos$Sub_metering_1,type='l',col='Black')
lines(time,datos$Sub_metering_2,type='l',col='red')
lines(time,datos$Sub_metering_3,type='l',col='blue')
legend('topright',lty=1,col=c('Black','Blue','Red'),legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),cex=.3)
plot(time,datos$Global_reactive_power,type='l')
