datos=read.table(file.choose(),header=T,sep=';')
datos=transform(datos,Date=as.Date(Date,format='%d/%m/%Y'))
datos=subset(datos,Date>as.Date('2007-01-31'))
datos=subset(datos,Date<as.Date('2007-02-03'))
x=paste(datos$Date,datos$Time)
time=strptime(x,format='%Y-%m-%d %H:%M:%S')
png(file='plot2.png')
plot(time,datos$Global_active_power,type='l')
